### ISSUE TITLE
Last ToDo's

### ISSUE THREAD

**Issue by xLacrima** [openvalidation/openvalidation-ide#159]
- [x]  persist active theme (cookie?)
- [x] Check highlighting if any word contains a keyword
- [x] Complete OpenAPI
  - [x] Rename heading
  - [x] Rename title 'schema' to 'schemas'
